config/routes.rb
Rails.application.routes.draw do
  resources :clientes do
    resources :vendas do
      resources :pagamentos, only: %i[new create edit update destroy]
    end
  end

  get '/relatorios', to: 'relatorios#index'
  root to: 'clientes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  has_many :clientes
  validates :nome, :uf, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :cidade
  has_many :vendas, dependent: :destroy
  validates :nome, :cliente_index, :cidade_id, presence: true
  validates :cliente_index, uniqueness: true

  def cria_cliente_index
    self.cliente_index = "#{nome} (#{Cidade.find_by(id: cidade_id).nome})"
  end
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
  belongs_to :venda
  validates :parcela, :dt_venc, :valor, presence: true
  scope :em_aberto, -> { where(dt_pgto: nil) }
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  has_many :pagamentos, dependent: :destroy
  validates :mercadorias, :valor, :data, presence: true

  def self.gerar(venda, forma_pgto)
    gera_pgtos(venda, forma_pgto) if venda.save
  end

  def self.gera_pgtos(venda, forma_pgto)
    if forma_pgto == 1
      venda.pagamentos.create(parcela: 1, dt_venc: venda.data, valor: venda.valor, dt_pgto: venda.data)
    else
      forma_pgto.times do |x|
        if x > 0
          venda.pagamentos.create(parcela: x, dt_venc: venda.data + x.month, valor: (venda.valor)/(forma_pgto - 1))
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)    
    respond_to do |format|
      @cliente.cria_cliente_index
      if @cliente.save        
        format.html { redirect_to @cliente, notice: 'O novo Cliente foi criado!' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update    
    respond_to do |format|
      if @cliente.update(cliente_params)
        @cliente.cria_cliente_index
        @cliente.save
        format.html { redirect_to @cliente, notice: 'Os dados do Cliente foram atualizados!' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'O Cliente foi excluído!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :cidade_id, :fone_fixo, :fone_celular)
    end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_cliente_venda, only: %i[new create edit update destroy]
  before_action :set_pagamento, only: %i[edit update destroy]

  # GET /vendas/new
  def new
    @pagamento = @venda.pagamentos.build
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @pagamento = @venda.pagamentos.build(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to cliente_venda_path(@cliente, @venda), notice: 'O pagamento foi registrada!' }
        format.json { render :show, status: :created, location: @pagamento }
      else
        format.html { render :new }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to cliente_venda_path(@cliente, @venda), notice: 'Os dados do Pagamento foram atualizados!' }
        format.json { render :show, status: :ok, location: @pagamento }
      else
        format.html { render :edit }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @pagamento.destroy
    respond_to do |format|
      format.html { redirect_to cliente_venda_path(@cliente, @venda), notice: 'O pagamento foi excluído!' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente_venda
    @cliente = Cliente.find(params[:cliente_id])
    @venda = @cliente.vendas.find(params[:venda_id])
  end

  def set_pagamento
    @pagamento = @venda.pagamentos.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pagamento_params
    params.require(:pagamento).permit(:parcela, :dt_venc, :valor, :dt_pgto)
  end
end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  def index
    @total_a_receber = Pagamento.em_aberto.sum("valor")
    @ultimos_recebimentos = {}
  end
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :get_cliente
  before_action :set_venda, only: [:show, :edit, :update, :destroy]
  before_action :set_pagamentos, only: :show

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = @cliente.vendas.order(data: :desc)
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = @cliente.vendas.build
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = @cliente.vendas.build(venda_params)

    respond_to do |format|
      if Venda.gerar(@venda, forma_pgto)
        format.html { redirect_to cliente_venda_path(@cliente, @venda), notice: 'A Venda foi registrada!' }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to cliente_venda_path(@cliente, @venda), notice: 'Os dados da Venda foram atualizados!' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to cliente_vendas_path(@cliente), notice: 'A Venda foi excluída!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_cliente
      @cliente = Cliente.find(params[:cliente_id])
    end

    def set_venda
      @venda = @cliente.vendas.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venda_params
      params.require(:venda).permit(:mercadorias, :data, :obs, :valor)
    end

    def forma_pgto
      params[:venda][:forma_pgto].to_i
    end

    def set_pagamentos
      @pagamentos = @cliente.vendas.find(params[:id]).pagamentos
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2>Corrija os seguintes erros para criar um novo cliente:</h2>
      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cidade_id %>
    <%= select("cliente", "cidade_id", Cidade.all.collect {|c| [ c.nome, c.id ] }) %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

    <div class="field">
    <%= form.label :fone_celular %>
    <%= form.text_field :fone_celular %>
  </div>

    <div class="field">
    <%= form.label :fone_fixo %>
    <%= form.text_field :fone_fixo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Detalhar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.cliente_index %></td>
        <td><%= link_to 'Detalhes', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Dados dos Cliente</h2>
<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= Cidade.find_by(id: @cliente.cidade_id).nome %>
</p>

<p>
  <strong>Telefone Celular:</strong>
  <%= @cliente.fone_celular %>
</p>

<p>
  <strong>Telefone Fixo:</strong>
  <%= @cliente.fone_fixo %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %> |
<%= link_to 'Registrar Venda', new_cliente_venda_path(@cliente) %> |
<%= link_to 'Ver Histórico de Vendas', cliente_vendas_path(@cliente) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cobrancaapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pagamentos/_form.html.erb
<%= form_with(model: @pagamento, url: [@cliente, @venda, @pagamento]) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2>Corrija os seguintes erros salvar um pagamento:</h2>
      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :parcela %>
    <%= form.number_field :parcela, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :dt_venc %>
    <%= form.date_select :dt_venc %>
  </div>

    <div class="field">
    <%= form.label :valor %>
    <%= form.number_field :valor, step: 0.01 %>
  </div>

    <div class="field">
    <%= form.label :dt_pgto %>
    <%= form.date_select :dt_pgto, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pagamentos/edit.html.erb
<h1>Editar Pagamento</h1>

<%= render 'form', cliente: @pagamento %>

<%= link_to 'Voltar', cliente_venda_path(@cliente, @venda) %>

app/views/pagamentos/new.html.erb
<h1>Registrar Pagamento</h1>

<%= render 'form', cliente: @pagamento %>

<%= link_to 'Voltar', cliente_venda_path(@cliente, @venda) %>

app/views/relatorios/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Estatísticas e Relatórios</h2>

<p>
  <strong>Valor Total de Pgtos a Receber:</strong>
  <%= "R$ #{@total_a_receber}" %>
</p>

<p>
  <strong>Relatório de Valores a Receber</strong>
</p>

<p>
  <strong>Total de Recebimentos Últimos 3 Meses:</strong>
  xxxx
</p>

<p>
  <strong>Relatório de Pagamentos</strong>

<p>
  <strong>Total de Vendas Últimos 3 Meses:</strong>
  xxxx
</p>

<p>
  <strong>Relatório de Vendas</strong>
</p>


</p>

<%= link_to 'Novo Cliente', new_cliente_path %> |
<%= link_to 'Lista de Clientes', clientes_path %> 

app/views/vendas/edit.html.erb
<h1>Editar Venda</h1>

<%= form_with(model: @venda, url: [@cliente, @venda]) do |form| %>
  <% if @venda.errors.any? %>
    <div id="error_explanation">
      <h2>Corrija os seguintes erros para registrar a venda:</h2>
      <ul>
        <% @venda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mercadorias %>
    <%= form.text_area :mercadorias %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.number_field :valor, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Detalhes', cliente_venda_path(@cliente) %> |
<%= link_to 'Voltar', cliente_vendas_path(@cliente) %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histórico de Vendas</h1>
<h2>Cliente <%= @cliente.cliente_index %></h2>
<table>
  <thead>
    <tr>
      <th>Data Venda</th>
      <th>Mercadoria</th>
      <th>Valor</th>
      <th>Observações</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.data%></td>
        <td><%= venda.mercadorias %></td>
        <td><%= venda.valor %></td>
        <td><%= venda.obs %></td>
        <td><%= link_to 'Detalhes', cliente_venda_path(venda.cliente_id, venda) %></td>
        <td><%= link_to 'Editar', edit_cliente_venda_path(venda.cliente_id, venda) %></td>
        <td><%= link_to 'Apagar', cliente_venda_path(venda.cliente_id, venda), method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Venda', new_cliente_venda_path %> |
<%= link_to 'Voltar', cliente_path(@cliente) %>

app/views/vendas/new.html.erb
<h1>Nova Venda</h1>

<%= form_with(model: @venda, url: [@cliente, @venda]) do |form| %>
  <% if @venda.errors.any? %>
    <div id="error_explanation">
      <h2>Corrija os seguintes erros para registrar a venda:</h2>
      <ul>
        <% @venda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mercadorias %>
    <%= form.text_area :mercadorias %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.number_field :valor, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs %>
  </div>

  <div class="field">
    <%= form.label :forma_pgto %>
    <%= form.select :forma_pgto, [['À Vista', 1], ['Parcelado 1x', 2], ['Parcelado 2x', 3], ['Parcelado 3x', 4], ['Parcelado 4x', 5]]%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', cliente_vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Detalhes da Venda</h2>

<p>
  <strong>Cliente:</strong>
  <%= @cliente.cliente_index %>
</p>

<p>
  <strong>Dt venda:</strong>
  <%= @venda.data %>
</p>

<p>
  <strong>Mercadorias:</strong>
  <%= @venda.mercadorias %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @venda.valor %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @venda.obs %>
</p>

<p>
  <strong>Pagamentos</strong>
</p>

<table>
  <thead>
    <tr>
      <th>Parc</th>
      <th>Venc</th>
      <th>Valor</th>
      <th>Dt_Pgto</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @pagamentos.each do |pgto| %>
      <tr>
        <td><%= pgto.parcela%></td>
        <td><%= pgto.dt_venc %></td>
        <td><%= pgto.valor %></td>
        <td><%= pgto.dt_pgto %></td>
        <td><%= link_to 'Editar', edit_cliente_venda_pagamento_path(@venda.cliente_id, @venda, pgto) %></td>
        <td><%= link_to 'Apagar', cliente_venda_pagamento_path(@venda.cliente_id, @venda, pgto), method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Editar', edit_cliente_venda_path(@cliente) %> |
<%= link_to 'Voltar', cliente_vendas_path(@cliente) %>|
<%= link_to 'Registrar Pagamento', new_cliente_venda_pagamento_path(@cliente, @venda, @pagamento) %>